// ***
//
// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
//
// ***
//
//
//
// Known that A XOR A = 0 and the XOR operator is commutative, the solution will be very straightforward.
// See 136. Single Number. Same idea.

char findTheDifference(string s, string t) {
    // You can initialize the char to whatever.
    char result = 0;

    for (char letter : s) {
        result ^= letter;
    }

    for (char letter : t) {
        result ^= letter;
    }

    return result;
}
